#%RAML 1.0 DataType
type: object
displayName: Coordinates
properties:
  x:
    type: number
    displayName: X
    required: true
    examples:
      Ex1: 0
  y:
    type: number
    displayName: Y
    required: true
    examples:
      Ex1: 0