#%RAML 1.0 Library
usage:
types:
  apiConfig: !include types/apiConfig.raml
  battlesnake: !include types/battlesnake.raml
  board: !include types/board.raml
  coordinate: !include types/coordinate.raml
  game: !include types/game.raml
  ruleset: !include types/ruleset.raml
  rulesetSettings: !include types/rulesetSettings.raml
  rulesetSettingsRoyale: !include types/rulesetSettingsRoyale.raml
  rulesetSettingsSquad: !include types/rulesetSettingsSquad.raml
  request: !include types/request.raml
  moveResponse: !include types/moveResponse.raml